/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KeyWord_NativeTest */

#ifndef _Included_KeyWord_NativeTest
#define _Included_KeyWord_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KeyWord_NativeTest
 * Method:    encryptData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KeyWord_NativeTest_encryptData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
